export default {
    GET_NEWSLIST:'GET_NEWSLIST',
    GET_HOTLIST:'GET_HOTLIST',
    GET_ESSENCELIST:'GET_ESSENCELIST',
    GET_QUESTIONDETAIL:'GET_QUESTIONDETAIL',
    GET_ANSWER:'GET_ANSWER',
    GET_ANSWERDETAIL:'GET_ANSWERDETAIL',
    GET_ANSWERFLOOR:'GET_ANSWERFLOOR',
    GET_GETCLIENTINFO:'GET_GETCLIENTINFO',
    GET_GETCLIENTRECIOPE:'GET_GETCLIENTRECIOPE',
    GET_GETCLIENTANSWER:'GET_GETCLIENTANSWER',
    GET_GETCLIENTACHIEVEMENTS:'GET_GETCLIENTACHIEVEMENTS'
}
