export default {
    GET_ACTIVITY:'GET_ACTIVITY',
    GET_ACTIVITY_DETAIL:'GET_ACTIVITY_DETAIL',
    GET_COMMUNITY:'GET_COMMUNITY',
    GET_COMMUNITY_DETAIL:'GET_COMMUNITY_DETAIL',
    GET_SHOW_LIST:'GET_SHOW_LIST',
}
