export default {

    GET_RECOMMENDLIST:'GET_RECOMMENDLIST',
    GET_KINDLIST:"GET_KINDLIST",
    GET_BAIKELIST:"GET_BAIKELIST",
    GET_SWIPERLIST:"GET_SWIPERLIST",
    GET_LESSONLIST:"GET_LESSONLIST",
    GET_VARIOUSLIST:"GET_VARIOUSLIST",
    GET_CATALOGLIST:"GET_CATALOGLIST",
    GET_TASKLIST:"GET_TASKLIST",
    GET_USERINFO:"GET_USERINFO",         //登录
    UP_LESSON:"UP_LESSON",
    UP_STUDENT:"UP_STUDENT",
    UP_NEWEST:"UP_NEWEST",
    UP_DISH:"UP_DISH",
    UP_FLOOR:"UP_FLOOR",
    UP_HOMEWORK:"UP_HOMEWORK",
    UP_CUURR:"UP_CUURR"
}

