export default {

    GET_RECOMMENDLIST:'GET_RECOMMENDLIST',
    GET_KINDLIST:"GET_KINDLIST",
    GET_BAIKELIST:"GET_BAIKELIST",
    GET_SWIPERLIST:"GET_SWIPERLIST",
    GET_LESSONLIST:"GET_LESSONLIST",
    GET_VARIOUSLIST:"GET_VARIOUSLIST",    //视频学堂页分类列表
    GET_MORE_LIST:"GET_MORE_LIST",        // 查看更多
    GET_CATALOGLIST:"GET_CATALOGLIST",    //课程目录
    GET_TASKLIST:"GET_TASKLIST",          //学员作业
    GET_USERINFO:"GET_USERINFO",         //登录
    UP_LESSON:"UP_LESSON",
    UP_STUDENT:"UP_STUDENT",
    UP_NEWEST:"UP_NEWEST",
    UP_DISH:"UP_DISH",
    UP_FLOOR:"UP_FLOOR",
    UP_HOMEWORK:"UP_HOMEWORK",
    UP_CUURR:"UP_CUURR",
    UP_CART:"UP_CART",
    CHANGE_ISFETCHING:"CHANGE_ISFETCHING"
}




