export default {
    GET_RECOMMENDLIST:'GET_RECOMMENDLIST',
    GET_KINDLIST:"GET_KINDLIST",
    GET_BAIKELIST:"GET_BAIKELIST",
    GET_SWIPERLIST:"GET_SWIPERLIST",
    GET_LESSONLIST:"GET_LESSONLIST",
    GET_VARIOUSLIST:"GET_VARIOUSLIST",
}
